docker:
  image: yegor256/rultor-image:1.9.1
install:
  - sudo gem install pdd -v 0.20.5
  - sudo gem install xcop -v 0.6
assets:
  secring.gpg: yegor256/home#assets/secring.gpg
  settings.xml: yegor256/home#assets/jcabi/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
merge:
  script: |-
    pdd --source=$(pwd) --verbose --file=/dev/null
    mvn clean install -Pqulice --errors --settings ../settings.xml
release:
  sensitive:
    - settings.xml
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Pjcabi --errors --settings ../settings.xml
    mvn clean site-deploy -Psite --errors --settings ../settings.xml