---
name: pdd
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pdd:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: g4s8/pdd-action@master
